/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author zawat
 */
public class edit_books extends javax.swing.JFrame {

    /**
     * Creates new form edit_books
     */
    public edit_books() {
        
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        b_Id = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        b_name = new javax.swing.JTextField();
        b_ISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_pub = new javax.swing.JTextField();
        b_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b_pages = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        but_back = new javax.swing.JButton();
        update1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Books");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(570, 0, 239, 73);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 60);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Book_ID");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(440, 60, 100, 22);

        b_Id.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        b_Id.setText("3"); // NOI18N
        b_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_IdMouseClicked(evt);
            }
        });
        jDesktopPane1.add(b_Id);
        b_Id.setBounds(550, 60, 210, 30);

        delete.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jDesktopPane1.add(delete);
        delete.setBounds(800, 180, 174, 46);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Book Name");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(440, 100, 100, 27);

        b_name.setEditable(false);
        b_name.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jDesktopPane1.add(b_name);
        b_name.setBounds(550, 100, 210, 30);

        b_ISBN.setEditable(false);
        b_ISBN.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jDesktopPane1.add(b_ISBN);
        b_ISBN.setBounds(550, 140, 210, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("ISBN");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(440, 140, 70, 22);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Publisher");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(440, 180, 90, 22);

        b_pub.setEditable(false);
        b_pub.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jDesktopPane1.add(b_pub);
        b_pub.setBounds(550, 180, 210, 30);

        b_price.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jDesktopPane1.add(b_price);
        b_price.setBounds(550, 220, 210, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("Price");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(440, 220, 50, 22);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Pages");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(440, 260, 60, 22);

        b_pages.setEditable(false);
        b_pages.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jDesktopPane1.add(b_pages);
        b_pages.setBounds(550, 260, 210, 30);

        search.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jDesktopPane1.add(search);
        search.setBounds(800, 60, 174, 46);

        but_back.setText("◀");
        but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_backActionPerformed(evt);
            }
        });
        jDesktopPane1.add(but_back);
        but_back.setBounds(20, 570, 120, 60);

        update1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(update1);
        update1.setBounds(800, 120, 174, 46);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 60, 1366, 688);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        delete();
        delete1();
    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
            conn con = new conn();
            if(evt.getSource()==search){
                String sql = "select * from book where idBook=?";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1,b_Id.getText());
                ResultSet rs = st.executeQuery();
                while(rs.next()){
                    b_name.setText(rs.getString("bookname"));
                    b_ISBN.setText(rs.getString("isbn"));
                    b_pub.setText(rs.getString("publisher"));
                    b_price.setText(rs.getString("price"));
                    b_pages.setText(rs.getString("pages"));
                }
                st.close();
                rs.close();
            }
        }
        catch(Exception e){
            System.out.println("Error!");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:
        new Main_panel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_but_backActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
        try{
            conn con = new conn();
            String sql = "Update book set price=? where idBook=?";
            PreparedStatement st = con.c.prepareCall(sql);
            st.setString(1,b_price.getText());
            st.setString(2,b_Id.getText());
            int i= st.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"record Updated Succesfully");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in Updating");
        }
    }//GEN-LAST:event_update1ActionPerformed

    private void b_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_IdMouseClicked
        // TODO add your handling code here:
        b_Id.setText("");
    }//GEN-LAST:event_b_IdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_books().setVisible(true);
            }
        });
    }
    private void delete() {
        try {
            conn con = new conn();
            String sql = "delete from book where idBook=?";
            PreparedStatement st = con.c.prepareStatement(sql);
            st.setString(1, b_Id.getText());
            int i = st.executeUpdate();
            if (i > 0)
                JOptionPane.showMessageDialog(null, "Book Deleted");
            else
                JOptionPane.showMessageDialog(null, "error in Issue");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b_ISBN;
    private javax.swing.JTextField b_Id;
    private javax.swing.JTextField b_name;
    private javax.swing.JTextField b_pages;
    private javax.swing.JTextField b_price;
    private javax.swing.JTextField b_pub;
    private javax.swing.JButton but_back;
    private javax.swing.JButton delete;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton search;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
private void delete1() {
        try {
            conn con = new conn();
            String sql = "delete from ret where idbook=?";
            PreparedStatement st = con.c.prepareStatement(sql);
            st.setString(1, b_Id.getText());
            int i = st.executeUpdate();
            if (i > 0){
                //JOptionPane.showMessageDialog(null, "Book issued");
            }
            else
                JOptionPane.showMessageDialog(null, "error in Deleting");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
	}
    }
}
