/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.Checkbox;
import java.sql.PreparedStatement;
import java.util.HashSet;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
/**
 *
 * @author zawat
 */
public class issue_box extends javax.swing.JFrame {

    /**
     * Creates new form issue_box
     */
    public issue_box() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        b_Id = new javax.swing.JTextField();
        b_Name = new java.awt.TextField();
        b_isbn = new java.awt.TextField();
        b_pub = new java.awt.TextField();
        b_price = new java.awt.TextField();
        s_name = new java.awt.TextField();
        s_course = new java.awt.TextField();
        s_sem = new java.awt.TextField();
        s_Id = new javax.swing.JTextField();
        but_back = new javax.swing.JButton();
        but_next = new javax.swing.JButton();
        issuedate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        pages = new java.awt.TextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 752));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Issue Book");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(600, 0, 239, 47);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -1, 1366, 50);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Book ID");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(340, 50, 80, 27);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Book Name");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(340, 90, 100, 27);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("ISBN");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(340, 130, 50, 27);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("Publisher");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(340, 170, 90, 27);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Price");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(340, 210, 60, 27);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Student ID");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(730, 50, 100, 27);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Student Name");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(730, 90, 130, 22);

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Semester");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(730, 130, 80, 27);

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setText("Course");
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(730, 170, 60, 22);

        b_Id.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jDesktopPane1.add(b_Id);
        b_Id.setBounds(480, 50, 210, 30);

        b_Name.setEditable(false);
        b_Name.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        b_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_NameActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_Name);
        b_Name.setBounds(480, 90, 210, 30);

        b_isbn.setEditable(false);
        b_isbn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        b_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_isbnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_isbn);
        b_isbn.setBounds(480, 130, 210, 30);

        b_pub.setEditable(false);
        b_pub.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        b_pub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pubActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_pub);
        b_pub.setBounds(480, 170, 210, 30);

        b_price.setEditable(false);
        b_price.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        b_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_priceActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_price);
        b_price.setBounds(480, 210, 210, 30);

        s_name.setEditable(false);
        s_name.setEnabled(false);
        s_name.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        s_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_nameActionPerformed(evt);
            }
        });
        jDesktopPane1.add(s_name);
        s_name.setBounds(870, 90, 210, 30);

        s_course.setEditable(false);
        s_course.setEnabled(false);
        s_course.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        s_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_courseActionPerformed(evt);
            }
        });
        jDesktopPane1.add(s_course);
        s_course.setBounds(870, 170, 210, 30);

        s_sem.setEditable(false);
        s_sem.setEnabled(false);
        s_sem.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        s_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_semActionPerformed(evt);
            }
        });
        jDesktopPane1.add(s_sem);
        s_sem.setBounds(870, 130, 210, 30);

        s_Id.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jDesktopPane1.add(s_Id);
        s_Id.setBounds(870, 50, 210, 30);

        but_back.setText("◀");
        but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_backActionPerformed(evt);
            }
        });
        jDesktopPane1.add(but_back);
        but_back.setBounds(10, 605, 100, 53);

        but_next.setText("▶");
        but_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nextActionPerformed(evt);
            }
        });
        jDesktopPane1.add(but_next);
        but_next.setBounds(1250, 605, 100, 53);
        jDesktopPane1.add(issuedate);
        issuedate.setBounds(480, 250, 210, 30);

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel12.setText("Date of Issuance");
        jDesktopPane1.add(jLabel12);
        jLabel12.setBounds(340, 250, 140, 27);

        search.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jDesktopPane1.add(search);
        search.setBounds(490, 320, 156, 52);

        pages.setEditable(false);
        pages.setEnabled(false);
        pages.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesActionPerformed(evt);
            }
        });
        jDesktopPane1.add(pages);
        pages.setBounds(870, 210, 210, 30);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel13.setText("Pages");
        jDesktopPane1.add(jLabel13);
        jLabel13.setBounds(730, 210, 50, 22);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 53, 1366, 702);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_NameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_b_NameActionPerformed

    private void b_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_isbnActionPerformed

    private void b_pubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_pubActionPerformed

    private void b_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_priceActionPerformed

    private void s_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_nameActionPerformed

    private void s_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_courseActionPerformed

    private void s_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_semActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_panel().setVisible(true);
    }//GEN-LAST:event_s_semActionPerformed

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_panel().setVisible(true);
    }//GEN-LAST:event_but_backActionPerformed

    private void but_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nextActionPerformed
        // TODO add your handling code here:
        try{
            conn con = new conn();
            if(evt.getSource()==but_next){
                String sql = "INSERT INTO issuebook(idbook,bookname,bookisbn,publisher,price,studentid,studentname,sem,course,pages,doi) values (?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1, b_Id.getText());
                st.setString(2, b_Name.getText());
                st.setString(3, b_isbn.getText());
                st.setString(4, b_pub.getText());
                st.setString(5, b_price.getText());
                st.setString(6, s_Id.getText());
                st.setString(7, s_name.getText());
                st.setString(8, s_sem.getText());
                st.setString(9, s_course.getText());
                st.setString(10, pages.getText());
                st.setString(11, ((JTextField) issuedate.getDateEditor().getUiComponent()).getText());
                int i = st.executeUpdate();
                if(i>0){
                    JOptionPane.showMessageDialog(null, "Processing....!");
                    delete();
                    delete1();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error..!");
                }
                
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_but_nextActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
            conn con = new conn();
            if(evt.getSource()==search){
                String sql = "select * from book where idBook=?";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1,b_Id.getText());
                ResultSet rs = st.executeQuery();
                while(rs.next()){
                    b_Name.setText(rs.getString("bookname"));
                    b_isbn.setText(rs.getString("isbn"));
                    b_pub.setText(rs.getString("publisher"));
                    b_price.setText(rs.getString("price"));
                    pages.setText(rs.getString("pages"));
                }
                st.close();
                rs.close();
            }
        }
        catch(Exception e){
            System.out.println("Error!");
        }
        
        try{
            conn con = new conn();
            if(evt.getSource()==search){
                String sql = "select * from student where idstudent=?";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1,s_Id.getText());
                ResultSet rs = st.executeQuery();
                while(rs.next()){
                    s_name.setText(rs.getString("stu_name"));
                    s_sem.setText(rs.getString("sem"));
                    s_course.setText(rs.getString("course"));
                }
                st.close();
                rs.close();
            }
        }
        catch(Exception e){
            System.out.println("Error!");
        }
        
    }//GEN-LAST:event_searchActionPerformed

    private void pagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue_box.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue_box.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue_box.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue_box.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issue_box().setVisible(true);
            }
        });
        
    }
    private void delete() {
        try {
            conn con = new conn();
            String sql = "delete from book where idBook=?";
            PreparedStatement st = con.c.prepareStatement(sql);
            st.setString(1, b_Id.getText());
            int i = st.executeUpdate();
            if (i > 0)
                JOptionPane.showMessageDialog(null, "Book Issued");
            else
                JOptionPane.showMessageDialog(null, "error in Issue");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b_Id;
    private java.awt.TextField b_Name;
    private java.awt.TextField b_isbn;
    private java.awt.TextField b_price;
    private java.awt.TextField b_pub;
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_next;
    private com.toedter.calendar.JDateChooser issuedate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField pages;
    private javax.swing.JTextField s_Id;
    private java.awt.TextField s_course;
    private java.awt.TextField s_name;
    private java.awt.TextField s_sem;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
private void delete1() {
        try {
            conn con = new conn();
            String sql = "delete from ret where idbook=?";
            PreparedStatement st = con.c.prepareStatement(sql);
            st.setString(1, b_Id.getText());
            int i = st.executeUpdate();
            if (i > 0)
                JOptionPane.showMessageDialog(null, "Book issued");
            else
                JOptionPane.showMessageDialog(null, "error in Deleting");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
	}
    }
}
