/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.*;
/**
 *
 * @author zawat
 */
public class Main_panel extends javax.swing.JFrame {

    /**
     * Creates new form Main_panel
     */
    public Main_panel() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITLE = new java.awt.Label();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        add_stud_but = new javax.swing.JButton();
        main_but_book = new javax.swing.JButton();
        main_but_stats = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        ret_book = new javax.swing.JButton();
        editbooks = new javax.swing.JButton();
        giv_book = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 752));
        jPanel1.setLayout(null);

        TITLE.setAlignment(java.awt.Label.CENTER);
        TITLE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TITLE.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        TITLE.setText("Library Management  System");
        jPanel1.add(TITLE);
        TITLE.setBounds(410, 10, 536, 50);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        add_stud_but.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_stud_but.setText("Add Student");
        add_stud_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_stud_butActionPerformed(evt);
            }
        });
        jDesktopPane1.add(add_stud_but);
        add_stud_but.setBounds(420, 80, 142, 66);

        main_but_book.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        main_but_book.setText("Add Book");
        main_but_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_but_bookActionPerformed(evt);
            }
        });
        jDesktopPane1.add(main_but_book);
        main_but_book.setBounds(40, 80, 142, 66);

        main_but_stats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        main_but_stats.setText("Overview");
        main_but_stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_but_statsActionPerformed(evt);
            }
        });
        jDesktopPane1.add(main_but_stats);
        main_but_stats.setBounds(230, 80, 142, 66);

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(370, 69, 625, 250);

        jDesktopPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ret_book.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ret_book.setText("Return Book");
        ret_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ret_bookActionPerformed(evt);
            }
        });

        editbooks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editbooks.setText("Edit books");
        editbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbooksActionPerformed(evt);
            }
        });

        giv_book.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giv_book.setText("Issue Book");
        giv_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giv_bookActionPerformed(evt);
            }
        });

        jDesktopPane3.setLayer(ret_book, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(editbooks, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(giv_book, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(giv_book, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(ret_book, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(editbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giv_book, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ret_book, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        jPanel1.add(jDesktopPane3);
        jDesktopPane3.setBounds(370, 343, 625, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 752);

        jMenu3.setText("Help");

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem1.setText("About Us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_but_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_but_bookActionPerformed
        // TODO add your handling code here:
        new add_Book().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_main_but_bookActionPerformed

    private void giv_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giv_bookActionPerformed
        // TODO add your handling code here:
        new issue_box().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_giv_bookActionPerformed

    private void editbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbooksActionPerformed
        // TODO add your handling code here:
        new edit_books().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editbooksActionPerformed

    private void add_stud_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_stud_butActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new add_stud().setVisible(true);
    }//GEN-LAST:event_add_stud_butActionPerformed

    private void ret_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ret_bookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ret_book().setVisible(true);
    }//GEN-LAST:event_ret_bookActionPerformed

    private void main_but_statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_but_statsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new OverView().setVisible(true);
    }//GEN-LAST:event_main_but_statsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new AboutUs().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new new_login().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        int confirmed = JOptionPane.showConfirmDialog(null,"You Want to quit?","exit",JOptionPane.YES_NO_OPTION);
        if(confirmed==JOptionPane.YES_OPTION){
            dispose();
        }
        else{
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label TITLE;
    private javax.swing.JButton add_stud_but;
    private javax.swing.JButton editbooks;
    private javax.swing.JButton giv_book;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton main_but_book;
    private javax.swing.JButton main_but_stats;
    private javax.swing.JButton ret_book;
    // End of variables declaration//GEN-END:variables
}
