/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Checkbox;
import java.sql.PreparedStatement;
import java.util.HashSet;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;

/**
 *
 * @author zawat
 */
public class new_login extends javax.swing.JFrame {

    /**
     * Creates new form new_login
     */
    public new_login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Login_ID = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Login_pass = new javax.swing.JPasswordField();
        but_next = new javax.swing.JButton();
        but_back = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN:");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(620, 20, 216, 65);

        Login_ID.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Login_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_IDActionPerformed(evt);
            }
        });
        jPanel1.add(Login_ID);
        Login_ID.setBounds(630, 110, 244, 29);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("UserName:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(500, 110, 126, 29);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 160, 126, 29);

        Login_pass.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Login_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_passActionPerformed(evt);
            }
        });
        jPanel1.add(Login_pass);
        Login_pass.setBounds(630, 160, 244, 29);

        but_next.setText("LOGIN");
        but_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nextActionPerformed(evt);
            }
        });
        jPanel1.add(but_next);
        but_next.setBounds(1220, 660, 120, 49);

        but_back.setText("◀");
        but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_backActionPerformed(evt);
            }
        });
        jPanel1.add(but_back);
        but_back.setBounds(20, 660, 120, 49);

        jButton3.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jButton3.setText("FORGOT PASSWORD?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(560, 310, 321, 49);

        CheckBox.setText("Show Password");
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBox);
        CheckBox.setBounds(630, 210, 130, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 752);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_IDActionPerformed

    private void Login_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_passActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new forgot_pass().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
       // TODO add your handling code here:
       this.setVisible(false);
       new LOGIN().setVisible(true);

    }//GEN-LAST:event_but_backActionPerformed

    private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxActionPerformed
        // TODO add your handling code here:
        if(CheckBox.isSelected()){
            Login_pass.setEchoChar((char)0);
        }
        else {
            Login_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_CheckBoxActionPerformed

    private void but_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nextActionPerformed
        // TODO add your handling code here:
        try{
            if(evt.getSource()==but_next){
                conn con = new conn();
                String sql = "Select * from users where idusers=? and Password=?";
                PreparedStatement st = con.c.prepareStatement(sql);
                
                st.setString(1,Login_ID.getText());
                st.setString(2,Login_pass.getText());
                
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    this.setVisible(false);
                    new Main_panel().setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid Login...!.");
                }
            }
        }
        catch(Exception e2)
        {
            e2.printStackTrace();
        }
    }//GEN-LAST:event_but_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private java.awt.TextField Login_ID;
    private javax.swing.JPasswordField Login_pass;
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_next;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
