/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.*;

/**
 *
 * @author zawat
 */
public class OverView extends javax.swing.JFrame {

    /**
     * Creates new form OverView
     */
    public OverView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        b_issue = new javax.swing.JButton();
        b_ret = new javax.swing.JButton();
        books = new javax.swing.JButton();
        but_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OverView");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 0, 239, 73);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 60);

        b_issue.setText("Books Issued");
        b_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_issueActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_issue);
        b_issue.setBounds(680, 150, 159, 84);

        b_ret.setText("Books Returned");
        b_ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_retActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_ret);
        b_ret.setBounds(680, 290, 159, 84);

        books.setText("Books");
        books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksActionPerformed(evt);
            }
        });
        jDesktopPane1.add(books);
        books.setBounds(683, 24, 159, 84);

        but_back.setText("◀");
        but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_backActionPerformed(evt);
            }
        });
        jDesktopPane1.add(but_back);
        but_back.setBounds(20, 570, 118, 67);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 61, 1366, 692);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksActionPerformed
        // TODO add your handling code here:
     this.setVisible(false);
     new Books().setVisible(true);
    }//GEN-LAST:event_booksActionPerformed

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_panel().setVisible(true);
    }//GEN-LAST:event_but_backActionPerformed

    private void b_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_issueActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new b_issue().setVisible(true);
    }//GEN-LAST:event_b_issueActionPerformed

    private void b_retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_retActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new b_ret().setVisible(true);
    }//GEN-LAST:event_b_retActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_issue;
    private javax.swing.JButton b_ret;
    private javax.swing.JButton books;
    private javax.swing.JButton but_back;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
