/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author zawat
 */
public class ret_book extends javax.swing.JFrame {

    /**
     * Creates new form ret_book
     */
    public ret_book() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        b_Name = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        course = new java.awt.TextField();
        s_name = new java.awt.TextField();
        b_pub = new java.awt.TextField();
        pages = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        returndate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        but_next = new javax.swing.JButton();
        but_back = new javax.swing.JButton();
        price = new java.awt.TextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        doi = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sem = new java.awt.TextField();
        isbn = new java.awt.TextField();
        s_Id = new java.awt.TextField();
        b_Id = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return Book");
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(683.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(569, 569, 569))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Student ID");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(650, 50, 100, 30);

        b_Name.setEditable(false);
        b_Name.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        b_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_NameActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_Name);
        b_Name.setBounds(429, 90, 210, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(650, 90, 50, 40);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Course");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(650, 250, 60, 30);

        course.setEditable(false);
        course.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        jDesktopPane1.add(course);
        course.setBounds(760, 250, 210, 30);

        s_name.setEditable(false);
        s_name.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        s_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_nameActionPerformed(evt);
            }
        });
        jDesktopPane1.add(s_name);
        s_name.setBounds(760, 90, 210, 30);

        b_pub.setEditable(false);
        b_pub.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        b_pub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pubActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_pub);
        b_pub.setBounds(760, 130, 210, 30);

        pages.setEditable(false);
        pages.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesActionPerformed(evt);
            }
        });
        jDesktopPane1.add(pages);
        pages.setBounds(429, 170, 210, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("pages");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(290, 170, 100, 30);

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel12.setText("Date of Return");
        jDesktopPane1.add(jLabel12);
        jLabel12.setBounds(290, 250, 170, 30);
        jDesktopPane1.add(returndate);
        returndate.setBounds(429, 250, 210, 30);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Book ID");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(290, 50, 70, 40);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Book Name");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(290, 90, 150, 40);

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Publisher");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(650, 130, 100, 30);

        search.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jDesktopPane1.add(search);
        search.setBounds(550, 330, 220, 60);

        but_next.setText("▶");
        but_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nextActionPerformed(evt);
            }
        });
        jDesktopPane1.add(but_next);
        but_next.setBounds(1180, 605, 150, 60);

        but_back.setText("◀");
        but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_backActionPerformed(evt);
            }
        });
        jDesktopPane1.add(but_back);
        but_back.setBounds(20, 605, 150, 60);

        price.setEditable(false);
        price.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jDesktopPane1.add(price);
        price.setBounds(760, 170, 210, 30);

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setText("price");
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(650, 170, 60, 30);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel13.setText("ISBN");
        jDesktopPane1.add(jLabel13);
        jLabel13.setBounds(290, 130, 100, 40);

        doi.setEditable(false);
        doi.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        doi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiActionPerformed(evt);
            }
        });
        jDesktopPane1.add(doi);
        doi.setBounds(429, 210, 210, 30);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Date of Issue");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(290, 210, 150, 30);

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel14.setText("Semester");
        jDesktopPane1.add(jLabel14);
        jLabel14.setBounds(650, 210, 80, 30);

        sem.setEditable(false);
        sem.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semActionPerformed(evt);
            }
        });
        jDesktopPane1.add(sem);
        sem.setBounds(760, 210, 210, 30);

        isbn.setEditable(false);
        isbn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(isbn);
        isbn.setBounds(429, 130, 210, 30);

        s_Id.setBackground(new java.awt.Color(255, 255, 255));
        s_Id.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        s_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_IdActionPerformed(evt);
            }
        });
        jDesktopPane1.add(s_Id);
        s_Id.setBounds(760, 50, 210, 30);

        b_Id.setBackground(new java.awt.Color(255, 255, 255));
        b_Id.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        b_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_IdActionPerformed(evt);
            }
        });
        jDesktopPane1.add(b_Id);
        b_Id.setBounds(429, 50, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_NameActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void s_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_nameActionPerformed

    private void b_pubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pubActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_panel().setVisible(true);
    }//GEN-LAST:event_b_pubActionPerformed

    private void pagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagesActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
            conn con = new conn();
            if(evt.getSource()==search){
                String sql = "select * from issuebook where idBook=?";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1,b_Id.getText());
                ResultSet rs = st.executeQuery();
                while(rs.next()){
                    b_Name.setText(rs.getString("bookname"));
                    isbn.setText(rs.getString("bookisbn"));
                    doi.setText(rs.getString("doi"));
                    pages.setText(rs.getString("pages"));
                    b_pub.setText(rs.getString("publisher"));
                    price.setText(rs.getString("price"));
                }
                st.close();
                rs.close();
            }
        }
        catch(Exception e){
            System.out.println("Error!");
        }

        try{
            conn con = new conn();
            if(evt.getSource()==search){
                String sql = "select * from student where idstudent=?";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1,s_Id.getText());
                ResultSet rs = st.executeQuery();
                while(rs.next()){
                    s_name.setText(rs.getString("stu_name"));
                    sem.setText(rs.getString("sem"));
                    course.setText(rs.getString("course"));
                }
                st.close();
                rs.close();
            }
        }
        catch(Exception e){
            System.out.println("Error1!");
        }

    }//GEN-LAST:event_searchActionPerformed

    private void but_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nextActionPerformed
        // TODO add your handling code here:
        try{
            conn con = new conn();
            if(evt.getSource()==but_next){
                String sql = "INSERT INTO book(idBook,bookname,isbn,publisher,price,pages) values (?,?,?,?,?,?)";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1, b_Id.getText());
                st.setString(2, b_Name.getText());
                st.setString(3, isbn.getText());
                st.setString(4, b_pub.getText());
                st.setString(5, price.getText());
                st.setString(6, pages.getText());
                int i = st.executeUpdate();
                if(i>0){
                    JOptionPane.showMessageDialog(null, "Successfully Book Returned.1.!");
                    delete();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error.2.!");
                }

            }
        }
        catch(HeadlessException | SQLException e){
            System.out.println("error in returning");
            System.out.println(e);
        }
        try{
            conn con = new conn();
            if(evt.getSource()==but_next){
                String sql = "INSERT INTO ret(idBook,bookname,isbn,studentid,studentname,doi,dor) values (?,?,?,?,?,?,?)";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1, b_Id.getText());
                st.setString(2, b_Name.getText());
                st.setString(3, isbn.getText());
                st.setString(4, s_Id.getText());
                st.setString(5, s_name.getText());
                st.setString(6, doi.getText());
                st.setString(7, ((JTextField) returndate.getDateEditor().getUiComponent()).getText());
                int i = st.executeUpdate();
                if(i>0){
                    JOptionPane.showMessageDialog(null, "Successfully Book Returned..!");
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error.2.!");
                }

            }
        }
        catch(HeadlessException | SQLException e){
            System.out.println("error in returning");
            System.out.println(e);
        }

    }//GEN-LAST:event_but_nextActionPerformed

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_panel().setVisible(true);
    }//GEN-LAST:event_but_backActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void doiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doiActionPerformed

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semActionPerformed

    private void isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnActionPerformed

    private void s_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_IdActionPerformed

    private void b_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_IdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ret_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ret_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ret_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ret_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ret_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField b_Id;
    private java.awt.TextField b_Name;
    private java.awt.TextField b_pub;
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_next;
    private java.awt.TextField course;
    private java.awt.TextField doi;
    private java.awt.TextField isbn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField pages;
    private java.awt.TextField price;
    private com.toedter.calendar.JDateChooser returndate;
    private java.awt.TextField s_Id;
    private java.awt.TextField s_name;
    private javax.swing.JButton search;
    private java.awt.TextField sem;
    // End of variables declaration//GEN-END:variables

    private void delete() {
        try {
            conn con = new conn();
            String sql = "delete from issuebook where idbook=?";
            PreparedStatement st = con.c.prepareStatement(sql);
            st.setString(1, b_Id.getText());
            int i = st.executeUpdate();
            if (i > 0)
                JOptionPane.showMessageDialog(null, "Book Returned");
            else
                JOptionPane.showMessageDialog(null, "error in Deleting");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
	}
    }
}
