/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Checkbox;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zawat
 */
public class SIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form SIGNUP
     */
    public SIGNUP() {
        initComponents();
        this.setLocationRelativeTo(null);
        setState(JFrame.MAXIMIZED_BOTH);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Sign_uname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sign_pw = new javax.swing.JPasswordField();
        Checkbox = new javax.swing.JCheckBox();
        but_back = new javax.swing.JButton();
        but_next = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Sign_name = new javax.swing.JTextField();
        Dropbox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Sign_Answer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 752));

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(51, 0, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGNUP");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(580, 0, 188, 77);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 190, 110, 30);

        Sign_uname.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Sign_uname.setText("UserName.");
        Sign_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Sign_unameFocusGained(evt);
            }
        });
        Sign_uname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_unameMouseClicked(evt);
            }
        });
        Sign_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_unameActionPerformed(evt);
            }
        });
        jPanel1.add(Sign_uname);
        Sign_uname.setBounds(660, 110, 196, 30);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("UserName: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 110, 110, 30);

        sign_pw.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        sign_pw.setText("Password");
        sign_pw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sign_pwFocusGained(evt);
            }
        });
        sign_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_pwActionPerformed(evt);
            }
        });
        jPanel1.add(sign_pw);
        sign_pw.setBounds(660, 190, 196, 30);

        Checkbox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Checkbox.setText("Show Password");
        Checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckboxActionPerformed(evt);
            }
        });
        jPanel1.add(Checkbox);
        Checkbox.setBounds(880, 200, 97, 20);

        but_back.setText("◀");
        but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_backActionPerformed(evt);
            }
        });
        jPanel1.add(but_back);
        but_back.setBounds(20, 665, 120, 49);

        but_next.setText("▶");
        but_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_nextMouseClicked(evt);
            }
        });
        but_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nextActionPerformed(evt);
            }
        });
        jPanel1.add(but_next);
        but_next.setBounds(1220, 665, 120, 49);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 150, 80, 30);

        Sign_name.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Sign_name.setText("Full Name.");
        Sign_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Sign_nameFocusGained(evt);
            }
        });
        Sign_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_nameMouseClicked(evt);
            }
        });
        Sign_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_nameActionPerformed(evt);
            }
        });
        jPanel1.add(Sign_name);
        Sign_name.setBounds(660, 150, 196, 30);

        Dropbox.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Where you were born?", "Your NickName?", "Favourite Sports?", "Your SuperHero?", "Dish you like the most?" }));
        Dropbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropboxActionPerformed(evt);
            }
        });
        jPanel1.add(Dropbox);
        Dropbox.setBounds(660, 230, 196, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Security Question");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 230, 160, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("Answer:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 270, 90, 30);

        Sign_Answer.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Sign_Answer.setText("Answer.");
        Sign_Answer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Sign_AnswerFocusGained(evt);
            }
        });
        Sign_Answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_AnswerActionPerformed(evt);
            }
        });
        jPanel1.add(Sign_Answer);
        Sign_Answer.setBounds(660, 270, 196, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sign_unameActionPerformed

    private void sign_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_pwActionPerformed

    private void CheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckboxActionPerformed
        // TODO add your handling code here:
        if(Checkbox.isSelected()){
            sign_pw.setEchoChar((char)0);
        }
        else {
            sign_pw.setEchoChar('*');
        }
    }//GEN-LAST:event_CheckboxActionPerformed

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:
        new LOGIN().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_but_backActionPerformed

    private void but_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nextActionPerformed
        // TODO add your handling code here:
        try{
            conn con = new conn();
            
            if(evt.getSource()== but_next){
                String sql = "INSERT INTO users(idusers,Name,Password,SecQues,Secans) values (?,?,?,?,?)";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1,Sign_uname.getText());
                st.setString(2,Sign_name.getText());
                st.setString(3,sign_pw.getText());
                st.setString(4,(String)Dropbox.getSelectedItem());
                st.setString(5,Sign_Answer.getText());
                
                int i = st.executeUpdate();
                if(i>0)
                {
                    JOptionPane.showMessageDialog(null, "successfully Created");
                }
                Sign_uname.setText("");
                Sign_name.setText("");
                sign_pw.setText("");
                Sign_Answer.setText("");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_but_nextActionPerformed

    private void Sign_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sign_nameActionPerformed

    private void DropboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropboxActionPerformed

    private void Sign_AnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_AnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sign_AnswerActionPerformed

    private void but_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_nextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_but_nextMouseClicked

    private void Sign_unameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_unameMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Sign_unameMouseClicked

    private void Sign_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_nameMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Sign_nameMouseClicked

    private void sign_pwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sign_pwFocusGained
        // TODO add your handling code here:
        sign_pw.setText("");
    }//GEN-LAST:event_sign_pwFocusGained

    private void Sign_unameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Sign_unameFocusGained
        // TODO add your handling code here:
        Sign_uname.setText("");
    }//GEN-LAST:event_Sign_unameFocusGained

    private void Sign_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Sign_nameFocusGained
        // TODO add your handling code here:
        Sign_name.setText("");
    }//GEN-LAST:event_Sign_nameFocusGained

    private void Sign_AnswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Sign_AnswerFocusGained
        // TODO add your handling code here:
        Sign_Answer.setText("");
    }//GEN-LAST:event_Sign_AnswerFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Checkbox;
    private javax.swing.JComboBox<String> Dropbox;
    private javax.swing.JTextField Sign_Answer;
    private javax.swing.JTextField Sign_name;
    private javax.swing.JTextField Sign_uname;
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField sign_pw;
    // End of variables declaration//GEN-END:variables
}
